#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kotaro Oshima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math


for line in sys.stdin:
    line = line.strip()
    if not line:
        sys.exit(1)
    try:
        x = float(line)
    except ValueError:    
        sys.exit(1)
    ans = x * 1.10
    ans_floor = math.floor(ans)
    print(ans_floor)
