#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kotaro Oshima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math


mode = sys.argv[1]


for line in sys.stdin:
    if line.strip():
        x = float(line)
        ans = x * (1.10 if mode == "-t" else 0.10)
        ans_floor = math.floor(ans)
        print(ans_floor)
