#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kotaro Oshima
# SPDX-License-Identifier: BSD-3-Clause

import sys
import math


lines = sys.stdin.readlines() 
ans = []

for line in lines:
    line = line.strip()
    if not line:
        continue
    try:
        x = float(line)
    except ValueError:    
        continue

    ans.append(str(math.floor(x * 1.10)))
print("\n".join(ans))
